name: Dependabot
on:
  push:
    paths:
      - ".github/workflows/dependabot.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: v2.3.4
        uses: actions/checkout@v2.3.4

      - name: v2
        uses: actions/checkout@v2

      - name: Verified creater v1.5.0
        uses: docker/setup-buildx-action@v1.5.0

      - name: v2.3.3
        uses: actions/checkout@v2.3.3

      - name: Verified creater v1.4.0
        uses: docker/setup-buildx-action@v1.4.0

      - name: Run
        run: echo "dummy"
