name: Dependabot
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Run
        run: echo "dummy"

      - name: v2.3.1
        uses: actions/checkout@v2.3.1

      - name: Verified creater
        uses: docker/setup-buildx-action@v1.6.0
