name: Dependabot
on:
  workflow_dispatch:

jobs:
  context:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: v2.3.4
        uses: actions/checkout@v2.3.4

      - name: v2
        uses: actions/checkout@v2

      - name: Verified creater
        uses: docker/setup-buildx-action@v1.5.0

      - name: Run
        run: echo "dummy"
